development:
  adapter: postgresql
  encoding: unicode
  database: prelude_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: prelude_test
  pool: 5
  username: postgres
  password: postgres
